service: sentiment-analyzer

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-prune-plugin

custom:
  wsgi:
    app: app.app  # Ensure this matches your Flask app's import path
  pythonRequirements:
    dockerizePip: false
    
package: 
  patterns:
    - '!venv/**'
    - '!__pycache__/**'
    - '!node_modules/**'
    - '!.serverless/**'
    - '!package-lock.json'
