service: sentiment-analyzer

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /analyze/{input_txt}
          method: GET
          requests:
            parameter:
              path:
                input_txt: true


plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-prune-plugin

custom:
  wsgi:
    app: app.app 
  pythonRequirements:
    dockerizePip: false
    
package: 
  patterns:
    - '!venv/**'
    - '!__pycache__/**'
    - '!node_modules/**'
    - '!.serverless/**'
    - '!package-lock.json'
